name: Container Request
description: Request a new container
title: "[Container Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your request. We always want to hear about new tools!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-needed
    attributes:
      label: What tool are you looking for and why?
      description: Also tell us if it is already available on dockerhub
      placeholder: Tell us what you see!
      value: "I need to use X for Y!"
    validations:
      required: true
