# base image
FROM ubuntu:bionic

# metadata
LABEL base.image="ubuntu:bionic"
LABEL container.version="1"
LABEL software="centroid"
LABEL software.version="v1.4"
LABEL description="Gene Allele Mutation Microbial Assessment"
LABEL website="https://github.com/rastanton/GAMMA/tree/v1.4"
LABEL license=""
LABEL maintainer="Rachael St. Jacques"
LABEL maintainer.email="rachael.stjacques@dgs.virginia.gov"

# install dependencies
RUN apt-get update && apt-get -y --no-install-recommends install \
    unzip \
    tar \
    python3.7 \
    python3-pip \
    gzip \
    wget \
    git \
    curl \
    make \
    g++ \
    ncbi-blast+ \
    hmmer && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

#install biopython
pip install biopython

# install amrfinder
RUN mkdir amrfinder && cd /amrfinder && \
    wget https://github.com/ncbi/amr/releases/download/amrfinder_v${AMRFINDER_VER}/amrfinder_binaries_v${AMRFINDER_VER}.tar.gz && \
    tar zxf amrfinder_binaries_v${AMRFINDER_VER}.tar.gz && \
    rm amrfinder_binaries_v${AMRFINDER_VER}.tar.gz && \
    mkdir /data

#install GAMMA
RUN git clone --no-check-certificate https://github.com/rastanton/GAMMA.git && \
    chmod +x GAMMA.py

# set PATH and locale settings for singularity compatibiliity
ENV PATH="${PATH}:\
    /amrfinder\
    /GAMMA"\
    LC_ALL=C

# download databases
RUN cd /amrfinder && amrfinder -u


WORKDIR /data
