# This called workflow builds a docker container, targeting the "app" stage and pushes the image to Docker Hub.

name: Build and deploy image

on:
  workflow_call:
    secrets:
      docker_username:
        required: true
      docker_access_token:
        required: true
    inputs:
      path_to_context:
        required: true
        type: string
      dockerfile_name:
        default: Dockerfile
        required: false
        type: string
      repository_name:
        default: staphb
        required: false
        type: string
      cache:
        required: true
        type: string
      container_name:
        required: true
        type: string
      tag:
        required: false
        default: latest
        type: string

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repo (+ download Git LFS dependencies)  # each job runs in an isolated environment, so need to check out the repo in each job
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers  # also need to set up the cache in each job, using the same prefix (here ${{ runner.os }}-buildx) makes it sharable between jobs
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-${{ inputs.cache }}
          key: ${{ runner.os }}-buildx-${{ inputs.cache }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.cache }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_access_token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.path_to_context }}
          file: ${{ inputs.path_to_context }}/${{ inputs.dockerfile_name }}
          target: app
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache-${{ inputs.cache }}
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-${{ inputs.cache }}-new # mode=max means export layers from all stage to cache
          tags: ${{ inputs.repository_name }}/${{ inputs.container_name }}:${{ inputs.tag }}

      - name: Move cache # apparently prevents the cache from growing in size forever
        run: |
          rm -rf /tmp/.buildx-cache-${{ inputs.cache }}
          mv /tmp/.buildx-cache-${{ inputs.cache }}-new /tmp/.buildx-cache-${{ inputs.cache }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
