# This caller workflow tests, builds, and pushes the image to Docker Hub.
# It also tests that a Singularity container can be run from the Docker image.
# Instructions: replace all the <placeholder> stubs in this template with values for your image.
# Some explanations come from: https://github.com/actions/starter-workflows/blob/main/automation/manual.yml

name: Deploy mlst 2.22.0 image

# This workflow should run when manually triggered by StaPH-B repo maintainer
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This job calls a workflow to build the image to the 'test' stage
  build-to-test:
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./mlst/2.22.0"  # Path to directory with Dockerfile and context, e.g. "./spades/3.12.0"; if you need to have the whole repo as context (e.g. to use files in test_data), use "."
      dockerfile_name: "Dockerfile"  # Name of the Dockerfile, should be "Dockerfile"; if you need to have the whole repo as context, use e.g. "./spades/3.12.0/Dockerfile"
      cache: "mlst"  # Use the program name as a nickname for a GitHub cache of your image's layers, e.g. "spades". The cache will speed up re-running the workflow.

  # This job calls a workflow to build the image to the 'app' stage and pushes the image to Docker Hub
  build-to-deploy:
    needs: build-to-test  # this jobs needs to run serially, after testing succeeds
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets: # these are the secret login credientials for pushing the containers to the repository
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      quay_username: ${{ secrets.quay_username }}
      quay_robot_token: ${{ secrets.quay_robot_token }}
    with:
      path_to_context: "./mlst/2.22.0"  # Same as above
      dockerfile_name: "Dockerfile"  # Same as above
      cache: "mlst"  # Same as above
      container_name: "mlst"  # The image name for Docker Hub, use the program name in lowercase, e.g. "spades"
      tag: "2.22.0"  # The image tag for Docker Hub, use the program version, e.g. "3.12.0"

  # This job calls a workflow to pull the image from Docker Hub and test that it can be run as a Singularity container
  run-singularity:
    needs: build-to-deploy  # test singularity run on newly pushed Docker image
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      image_name: "mlst:2.22.0"  # The image to pull, e.g. "spades:3.12.0"
