name: Deploy bcftools image

on: workflow_dispatch

jobs:
  build-to-test:
    uses: StaPH-B/docker-builds/.github/workflows/build-to-test.yml@master
    with:
      path_to_context: "./bcftools/1.15"  # Path to directory with Dockerfile and context, e.g. "./spades/3.12.0"; if you need to have the whole repo as context (e.g. to use files in test_data), use "."
      dockerfile_name: "Dockerfile"  # Name of the Dockerfile, should be "Dockerfile"; if you need to have the whole repo as context, use e.g. "./spades/3.12.0/Dockerfile"
      cache: "bcftools"  # Use the program name as a nickname for a GitHub cache of your image's layers, e.g. "spades". The cache will speed up re-running the workflow.

  build-to-deploy:
    needs: build-to-test  # this jobs needs to run serially, after testing succeeds
    uses: StaPH-B/docker-builds/.github/workflows/build-to-deploy.yml@master
    secrets: # these are the secret login credientials for pushing the containers to the repository
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    with:
      path_to_context: "./bcftools/1.15"  # Same as above
      dockerfile_name: "Dockerfile"  # Same as above
      cache: "bcftools"  # Same as above
      container_name: "bcftools"
      tag: "1.15"

  run-singularity:
    needs: build-to-deploy
    uses: StaPH-B/docker-builds/.github/workflows/run-singularity.yml@master
    with:
      image_name: "bcftools:1.15"
