##### ---------------------------------------------------------- #####
##### This caller workflow tests an image                        #####
##### It takes manual input as to which tool and version to test #####
##### ---------------------------------------------------------- #####

name: Manual test

on:
  workflow_dispatch:
    inputs:
      tool:
        description: "Tool to test. Must match filepath: /build-files/<tool>/version/Dockerfile"
        required: true
      version:
        description: "Version to test. Must match filepath: /build-files/tool/<version>/Dockerfile"
        required: true

jobs:
  # This job calls a workflow to build the image to the 'test' stage
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./build-files/${{ github.event.inputs.tool }}/${{ github.event.inputs.version }}"
      dockerfile_name: "Dockerfile"
      cache: ${{ github.event.inputs.tool }}
