
name: Test DSK image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "dsk/0.0.100/Dockerfile"

jobs:

  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "./dsk/0.0.100"
      dockerfile_name: "Dockerfile"
      cache: "dsk"
