name: Test bcftools image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'bcftools/*/Dockerfile'

jobs:
  build-to-test:
    uses: ./.github/workflows/build-to-test.yml
    with:
      path_to_context: "bcftools/1.15"
      dockerfile_name: "Dockerfile"
      cache: "bcftools"
